<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNHUiPgh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNHUiPgh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNHUiPgh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNHUiPgh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNHUiPgh\App_KernelDevDebugContainer([
    'container.build_hash' => 'NHUiPgh',
    'container.build_id' => 'e2ed2ece',
    'container.build_time' => 1578344937,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNHUiPgh');
